import SideBar from "@/components/sidebar";
import NavBar from "@/components/navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-row">
          {/* <div className="col-span-1">
            <SideBar />
          </div> */}
        </div>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
